#!/usr/bin/env python3
#
# DaisyOS - main firmware for the Daisy computer.
# Copyright (C) 2026 Joe Cassara
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Turns Z-machine story files into a flash-resident C++ array.

The SAM3X maps its flash into the normal address space, so a story compiled in
as a const array can be read with a plain subscript and never needs to be
copied to RAM. Only the dynamic region, given by header word 0x0E, is
allocated at runtime.

Story files are not distributed with DaisyOS. Supply your own:

    tools/mkstory.py ZORK1.DAT > src/zmachine/zm_stories.cpp

Several stories can be given at once, but mind the flash budget: each is
80-90 KB against the Due's 512 KB, of which DaisyOS itself uses about 160 KB.

With more than one story built in, the ZORK command offers a menu, and the
name shown there is the file name unless you give a better one:

    tools/mkstory.py "Zork I=ZORK1.DAT" "Zork II=ZORK2.DAT" > ...

Keep the names short. The menu is 40 columns wide and indents them by four.
"""

import os
import struct
import sys

HEADER = """/*
 * DaisyOS - main firmware for the Daisy computer.
 * Copyright (C) 2026 Joe Cassara
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Generated by tools/mkstory.py. Do not edit.
 *
 * Story images live in flash and are read in place. Editing this file by hand
 * means regenerating it the next time a story changes, so change the tool
 * instead.
 */

#ifndef ZM_HOST_BUILD

#include "zmachine/zm_story.h"

"""


def describe(data):
    """Returns (version, dynamic_size) from the story header."""
    version = data[0]
    static_base = struct.unpack(">H", data[0x0E:0x10])[0]
    return version, static_base


def emit_array(name, data, out):
    out.write("static const uint8_t %s[] = {\n" % name)
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.write("    " + "".join("0x%02x," % b for b in chunk) + "\n")
    out.write("};\n\n")


def main(argv):
    if len(argv) < 2:
        sys.stderr.write(__doc__)
        return 2

    out = sys.stdout
    out.write(HEADER)

    entries = []
    total = 0

    for index, arg in enumerate(argv[1:]):
        # "Name=path" gives the menu something friendlier than a file name.
        if "=" in arg:
            title, path = arg.split("=", 1)
            title = title.strip()
        else:
            path = arg
            title = None

        with open(path, "rb") as handle:
            data = handle.read()

        if len(data) < 64:
            sys.stderr.write("%s: too short to be a story file\n" % path)
            return 1

        version, dynamic = describe(data)
        if version < 1 or version > 8:
            sys.stderr.write("%s: not a Z-machine story (version byte %d)\n"
                             % (path, version))
            return 1

        if not title:
            title = os.path.splitext(os.path.basename(path))[0]
        if len(title) > 30:
            sys.stderr.write("%s: name is too long for the menu\n" % title)
            return 1
        if '"' in title or "\\" in title:
            sys.stderr.write("%s: name cannot contain a quote or backslash\n"
                             % title)
            return 1
        symbol = "kStory%d" % index
        total += len(data)

        sys.stderr.write(
            "%-14s v%d  %6d bytes flash, %5d bytes RAM when running\n"
            % (title, version, len(data), dynamic))

        out.write("/* %s: Z-machine version %d, %d bytes.\n"
                  " * Dynamic memory is %d bytes; the remaining %d are read\n"
                  " * from flash and never occupy RAM. */\n"
                  % (title, version, len(data), dynamic, len(data) - dynamic))
        emit_array(symbol, data, out)
        entries.append((title, symbol, len(data)))

    out.write("const ZmStory kZmStories[] = {\n")
    for title, symbol, size in entries:
        out.write('    {"%s", %s, %d},\n' % (title, symbol, size))
    out.write("};\n\n")
    out.write("const uint8_t kZmStoryCount = %d;\n\n" % len(entries))
    out.write("#endif /* !ZM_HOST_BUILD */\n")

    sys.stderr.write("%-14s     %6d bytes of flash total\n" % ("", total))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
