# DaisyOS - main firmware for the Daisy computer.
# Copyright (C) 2026 Joe Cassara
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
png_to_chars.py — Convert a PNG image to a DaisyBASIC character bitmap binary.

Each 8×8 pixel block becomes 8 bytes (one byte per scanline).
  Bit 7 (MSB) = leftmost pixel of that row.
  1 = white (or near-white), 0 = everything else.

Characters are ordered left-to-right, top-to-bottom across the image,
matching the layout produced by FILLBLOCK on screen.

The output binary is suitable for LOADCHAR:
  LOADCHAR filename [,char|gfx [,startIndex]]

Usage:
  python3 png_to_chars.py input.png output.bin [--threshold N] [--start N]
                          [--charrom [NAME]]

  --threshold N   Per-channel brightness cutoff for "white" (0-255, default 128).
                  A pixel is white if R >= N and G >= N and B >= N.

  --start N       First character index in the ROM (0-255, default 0).
                  Used to place characters at the correct offset in --charrom output.

  --charrom [NAME]
                  Instead of (or in addition to) the binary, write a C header
                  containing a full 2048-byte PROGMEM array in the same transposed
                  layout as charROM in DaisyVideo/src/main.cpp.
                  The array is named NAME (default: stem of the output filename).
                  Characters outside the converted range are zeroed.
                  Layout: array[ch + 256*row]  — 8 planes of 256 bytes each.
                  The output file is the output path with its extension replaced by .h.
"""

import sys
import os
import argparse

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required.  Run: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def extract_bitmaps(input_path: str, threshold: int) -> tuple[list[list[int]], int, int]:
    """Return (bitmaps, cols, rows).  bitmaps[i] is a list of 8 bytes for char i."""
    img = Image.open(input_path).convert("RGBA")
    width, height = img.size

    if width % 8 != 0 or height % 8 != 0:
        print(
            f"Error: image is {width}×{height} px — dimensions must be multiples of 8.",
            file=sys.stderr,
        )
        sys.exit(1)

    cols = width // 8
    rows = height // 8
    num_chars = cols * rows

    if num_chars > 255:
        print(
            f"Error: image produces {num_chars} characters ({cols}×{rows}) — maximum is 255.",
            file=sys.stderr,
        )
        sys.exit(1)

    pixels = img.load()
    bitmaps = []

    for char_row in range(rows):
        for char_col in range(cols):
            base_x = char_col * 8
            base_y = char_row * 8
            char_bytes = []
            for scan_y in range(8):
                byte = 0
                for scan_x in range(8):
                    r, g, b, a = pixels[base_x + scan_x, base_y + scan_y]
                    if a >= threshold and r >= threshold and g >= threshold and b >= threshold:
                        byte |= 1 << (7 - scan_x)
                char_bytes.append(byte)
            bitmaps.append(char_bytes)

    return bitmaps, cols, rows


def write_binary(bitmaps: list[list[int]], output_path: str) -> None:
    data = bytearray()
    for char_bytes in bitmaps:
        data.extend(char_bytes)
    with open(output_path, "wb") as f:
        f.write(data)
    print(f"  Written : {len(data)} bytes → {output_path}")


def write_charrom(bitmaps: list[list[int]], output_path: str, array_name: str,
                  start_index: int, input_path: str) -> None:
    """Write a C header with a full 2048-byte PROGMEM array in charROM layout.

    Layout matches DaisyVideo: array[ch + 256*row]
    — 8 planes of 256 bytes, plane k holds scan-row k of every character.
    """
    rom = [[0] * 256 for _ in range(8)]
    for i, char_bytes in enumerate(bitmaps):
        ch = start_index + i
        if ch > 255:
            break
        for row in range(8):
            rom[row][ch] = char_bytes[row]

    num_chars = len(bitmaps)
    end_index = min(start_index + num_chars - 1, 255)

    lines = []
    lines.append(f"// Generated by png_to_chars.py from {os.path.basename(input_path)}")
    lines.append(f"// {num_chars} characters (indices {start_index}–{end_index})")
    lines.append(f"// Layout: {array_name}[ch + 256*row]  — 8 scan-row planes × 256 chars")
    lines.append(f"PROGMEM const byte {array_name} [] = {{")

    for row in range(8):
        hex_vals = ",".join(f"0x{b:02X}" for b in rom[row])
        lines.append(f"  // row {row}")
        lines.append(f"  {hex_vals},")

    lines.append("};")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written : 2048 bytes ({array_name}[]) → {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert a PNG to a DaisyBASIC character bitmap binary."
    )
    parser.add_argument("input", help="Input PNG file")
    parser.add_argument("output", help="Output binary file (or .h stem when using --charrom)")
    parser.add_argument(
        "--threshold",
        type=int,
        default=128,
        metavar="N",
        help="Per-channel brightness threshold for white (0-255, default 128)",
    )
    parser.add_argument(
        "--start",
        type=int,
        default=0,
        metavar="N",
        help="Starting character index in the ROM (0-255, default 0)",
    )
    parser.add_argument(
        "--charrom",
        nargs="?",
        const="",
        metavar="NAME",
        help="Also write a C header with a full PROGMEM charROM-style array. "
             "NAME defaults to the output filename stem.",
    )
    args = parser.parse_args()

    if not (0 <= args.threshold <= 255):
        print("Error: --threshold must be between 0 and 255.", file=sys.stderr)
        sys.exit(1)

    if not (0 <= args.start <= 255):
        print("Error: --start must be between 0 and 255.", file=sys.stderr)
        sys.exit(1)

    bitmaps, cols, rows = extract_bitmaps(args.input, args.threshold)
    num_chars = len(bitmaps)

    print(f"  Image   : {cols*8}×{rows*8} px")
    print(f"  Grid    : {cols} cols × {rows} rows = {num_chars} characters")
    print(f"  Start   : index {args.start}  (chars {args.start}–{args.start + num_chars - 1})")
    print(f"  White ≥ : {args.threshold} per channel")

    write_binary(bitmaps, args.output)

    if args.charrom is not None:
        array_name = args.charrom if args.charrom else os.path.splitext(os.path.basename(args.output))[0]
        stem = os.path.splitext(args.output)[0]
        h_path = stem + ".h"
        write_charrom(bitmaps, h_path, array_name, args.start, args.input)


if __name__ == "__main__":
    main()
